export const subCategoryImages = {
  //category 01
  'Hole Bit': require('../assets/images/hole.png'),
  'Drill Bit': require('../assets/images/drill.png'),
  'Diamond Wheel': require('../assets/images/diamond.png'),
  'Cutting Wheel': require('../assets/images/cut.png'),
  'Grinding Wheel': require('../assets/images/grind.png'),
  'Saw Blade': require('../assets/images/saw.png'),
  'Flap Disc': require('../assets/images/flap.png'),
  'Sticker Pad': require('../assets/images/sPad.png'),
  'Sticker Paper': require('../assets/images/sPaper.png'),
  'Polishing Pad': require('../assets/images/polish.png'),
  'Sharpen Wheel ': require('../assets/images/sharpen.png'),
  'Gray Cutter': require('../assets/images/grayCutter.png'),
  'Planer Blade': require('../assets/images/planner.png'),
  'Cup Brush': require('../assets/images/cupBrush.png'),
  'Grinding Pad': require('../assets/images/grindP.png'),
  'Router Bits': require('../assets/images/routerBits.png'),

  //category 02
  'Screwdriver ': require('../assets/images/srew.png'),
  'Combination Wrench': require('../assets/images/comW.png'),
  'L Wrench': require('../assets/images/l.png'),
  'T Wrench\t': require('../assets/images/t.png'),
  'Y Wrench\t': require('../assets/images/y.png'),
  'X Wrench\t': require('../assets/images/x.png'),
  'Ratchet Wrench': require('../assets/images/ratchet.png'),
  'Combination Wrench Set': require('../assets/images/comWrench.png'),
  'Hacksaw Frame': require('../assets/images/haksaw.png'),
  'Combination Pliers': require('../assets/images/comPiler.png'),
  'Nose Pliers': require('../assets/images/nosePiler.png'),
  'Cutter Pliers': require('../assets/images/cutterP.png'),
  'Ball Cutter ': require('../assets/images/ball.png'),
  'Oil Filter Wrench ': require('../assets/images/oil.png'),
  'Aviation Snip ': require('../assets/images/aviation.png'),
  'Hacksaw Blade': require('../assets/images/hakblade.png'),
  'Pruning Shears': require('../assets/images/snip.png'),
  'Pipe Wrench': require('../assets/images/pipe.png'),
  'Crimping Pliers ': require('../assets/images/crimping.png'),
  'Adjustable Wrench': require('../assets/images/wrench.png'),
  'Tinman Snips': require('../assets/images/tinman.png'),
  'Shoe Cutter': require('../assets/images/shoe.png'),
  'Claw Hammer ': require('../assets/images/clawH.png'),
  'Tinner Hammer ': require('../assets/images/tinner.png'),
  'Sledge Hammer': require('../assets/images/sledge.png'),
  'Rubber Hammer ': require('../assets/images/rubber.png'),
  'Jel Hammer': require('../assets/images/gel.png'),
  'Wood Chisel': require('../assets/images/chisel.png'),
  'Mason Trowels': require('../assets/images/mason.png'),
  'Hand Saw': require('../assets/images/hsaw.png'),
  'Try Square': require('../assets/images/tryS.png'),
  'Sprit Level ': require('../assets/images/sprit.png'),
  'Hex Key Set': require('../assets/images/hex.png'),
  'Punching Pliers ': require('../assets/images/punch.png'),
  'Silicon Gun': require('../assets/images/sGun.png'),
  'Pop Rivert Gun': require('../assets/images/pGun.png'),
  'Wrapping Bar': require('../assets/images/wrap.png'),
  'Roller Brush': require('../assets/images/roller.png'),
  'Paint Brush': require('../assets/images/paint.png'),
  'Wire Brush': require('../assets/images/wire.png'),
  Scrapper: require('../assets/images/scrap.png'),
  'Glass Cutter': require('../assets/images/glass.png'),
  'Finishing Trowel': require('../assets/images/finish.png'),
  'Hand Sander': require('../assets/images/sandner.png'),

  //category 03

  'Nipple With Wire': require('../assets/images/nipleW.png'),
  'Box Socket': require('../assets/images/boxS.png'),
  'Spray Gun': require('../assets/images/sprayG.png'),
  'Oil Gun': require('../assets/images/oilG.png'),
  'Hack Saw Blade': require('../assets/images/hakblade.png'),
  'Grease Gun': require('../assets/images/greaseG.png'),
  'Sprinkler ': require('../assets/images/sprinkler.png'),
  'Measurering Tape ': require('../assets/images/mTape.png'),
  'Compressor Tap': require('../assets/images/comTap.png'),
  Lamp: require('../assets/images/lamp.png'),
  'Pickaxe ': require('../assets/images/pix.png'),
  Mamoty: require('../assets/images/mam.png'),
  'Garden Sprayers ': require('../assets/images/gardenS.png'),
  Hose: require('../assets/images/hose.png'),
  'Steel Tape': require('../assets/images/steelT.png'),
  'Measurering Tape': require('../assets/images/mTape.png'),
  Nosal: require('../assets/images/nozzle.png'),
  'Hall Saw Set': require('../assets/images/hallSet.png'),
  'Air Guns': require('../assets/images/air.png'),
  'Switch ': require('../assets/images/switch.png'),
  'Floter Switch ': require('../assets/images/fSwitch.png'),
  'Pad Lock': require('../assets/images/padL.png'),
  'L Bracket': require('../assets/images/lBra.png'),
  'Roller Tray': require('../assets/images/rollerT.png'),
  'Chain Lock': require('../assets/images/chaiL.png'),
  'Wall Plug': require('../assets/images/wallP.png'),
  'Combination Stone': require('../assets/images/comSton.png'),
  'Double Side Tape': require('../assets/images/dubT.png'),
  'Flashing Tape': require('../assets/images/flash.png'),
  'Duct Tape': require('../assets/images/duct.png'),
  'Mesh Tape': require('../assets/images/mesh.png'),
  'Sand Paper Roll': require('../assets/images/sandP.png'),
  'Tower Bolt': require('../assets/images/towerB.png'),
  'Hasp & Staple': require('../assets/images/hasp.png'),
  'Caster Wheel': require('../assets/images/caster.png'),
  'Trolley Wheel': require('../assets/images/trolly.png'),
  'Tintex Nails': require('../assets/images/tintex.png'),
  'Concrete Nails': require('../assets/images/conNail.png'),
  'Jaguar Nails': require('../assets/images/jaguar.png'),
  'Umbrella Nails': require('../assets/images/umbNail.png'),
  'Roofing Nails': require('../assets/images/roofN.png'),
  'Drywall Screw ': require('../assets/images/dryS.png'),
  'Amano Nails': require('../assets/images/amano.png'),
  'Mouse Box': require('../assets/images/mouse.png'),
  'Curtain Runners': require('../assets/images/curtain.png'),
  'Key Cylinder': require('../assets/images/keyS.png'),
  'Tap Connector': require('../assets/images/tapC.png'),
  Scale: require('../assets/images/scale.png'),
  'Well Pulley': require('../assets/images/wellP.png'),
  'Dog Chain ': require('../assets/images/dog.png'),
  'Gutter Chain ': require('../assets/images/gutter.png'),
  'Door Stopper': require('../assets/images/stopD.png'),
  'Soldering Iron': require('../assets/images/solder.png'),
  'Booster Cable': require('../assets/images/boost.png'),
  'Water Seal': require('../assets/images/waterS.png'),
  'Pop Rivert ': require('../assets/images/pop.png'),
  'Magnetic Nut Socket': require('../assets/images/magSo.png'),
  'Cup Hooks': require('../assets/images/cupH.png'),
  'Hose Clip': require('../assets/images/hclip.png'),
  'Pipe Clip': require('../assets/images/pipC.png'),
  'Pantry Magnet': require('../assets/images/pM.png'),
  Capacitor: require('../assets/images/capa.png'),
  'Cable Tie': require('../assets/images/cableT.png'),
  Bearing: require('../assets/images/bear.png'),
  'Safety Helmet ': require('../assets/images/safeH.png'),
  'Mounted Grinding Point ': require('../assets/images/mPg.png'),
  'Glass Cutter ': require('../assets/images/glassC.png'),
  'Carbon Brush ': require('../assets/images/carbon.png'),
  'Gloves ': require('../assets/images/glove.png'),
  'Mosquito Mesh ': require('../assets/images/mosmes.png'),
  'Welded Mesh': require('../assets/images/welded.png'),
  'Shading Net': require('../assets/images/shaded.png'),
  'Green Mesh': require('../assets/images/green.png'),
  'Tarpaulin Roll': require('../assets/images/tarpau.png'),
  'Curtain Wire': require('../assets/images/wireC.png'),
  'Curtain Hooks': require('../assets/images/hook.png'),
  'Kitchen Sink ': require('../assets/images/kSink.png'),

  //category 04
  'Basin Tap': require('../assets/images/basinT.png'),
  'Garden Tap': require('../assets/images/gardernT.png'),
  'Bip Tap': require('../assets/images/bipT.png'),
  'Sink Tap': require('../assets/images/sinkT.png'),
  'Angle Valve ': require('../assets/images/angleV.png'),
  'Concealed Valve ': require('../assets/images/conV.png'),
  'Gully Box': require('../assets/images/gullyB.png'),
  'Gully Cover': require('../assets/images/gullyC.png'),
  'Biddy Spray Set': require('../assets/images/bKit.png'),
  'Sink West': require('../assets/images/sWest.png'),
  'Basin West': require('../assets/images/bWest.png'),
  Shower: require('../assets/images/shower.png'),
  'Hand Shower': require('../assets/images/handS.png'),
  'Biddy Head': require('../assets/images/bidget.png'),
  'Flexible Hose': require('../assets/images/fHose.png'),
  'Non Return Valve ': require('../assets/images/nonV.png'),
  'Ball Float Valve': require('../assets/images/ballVal.png'),
  'Ball Valve': require('../assets/images/ballV.png'),
  'Magic Hose ': require('../assets/images/magic.png'),
  'Magic Bend': require('../assets/images/magicB.png'),
  'L Bend': require('../assets/images/lB.png'),
  'Cistern Fitting Set': require('../assets/images/chrisF.png'),
  'Cistern Fitting Handel': require('../assets/images/chrisH.png'),
  'Sanitary Fixing Set': require('../assets/images/sanF.png'),
  'Towel Bar': require('../assets/images/towelB.png'),
  'Soap Case ': require('../assets/images/soapC.png'),
  'Shelf Soap Tray': require('../assets/images/soapT.png'),
  'Outlat Hose': require('../assets/images/outlet.png'),
  'Inlet Hose': require('../assets/images/inlet.png'),
  'Combined Valve': require('../assets/images/comVall.png'),
  'Commode Seat Cover': require('../assets/images/comSeat.png'),

  //category 05
  'Iron Oxide Bag': require('../assets/images/ibag.png'),
  'Iron Oxide Beral': require('../assets/images/baral.png'),
  'Iron Oxide Tin': require('../assets/images/tin.png'),

  //category 06
  'Appo Lock': require('../assets/images/appo.png'),
  'Drawer Lock ': require('../assets/images/drawer.png'),
  'Mortice Lock ': require('../assets/images/mortice.png'),
  'Door Lock': require('../assets/images/doorr.png'),

  default: require('../assets/images/tools.png'),
};
